// src/composables/usePublications.ts
import { ref, onMounted } from 'vue'
import type { Publication } from '@/types'

export function usePublications() {
  const publications = ref<Publication[]>([])
  const loading = ref(true)
  const error = ref<string | null>(null)

  const fetchPublications = async () => {
    loading.value = true
    error.value = null
    try {
      await new Promise(resolve => setTimeout(resolve, 800)) // 模拟延迟

      publications.value = [
        {
              id: 1,
              title: "Sequential Collaborative Detection Strategy on ADS-B Data Attack",
              authors: ["Tengyao Li", "Buhong Wang"],
              venue: "International Journal of Critical Infrastructure Protection",
              year: 2019,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.ijcip.2018.11.003",
              code: "#",
              highlight: false,
              bibtex: `@article{liSequentialCollaborativeDetection2019,
              title = {Sequential Collaborative Detection Strategy on ADS-B Data Attack},
              author = {Li, Tengyao and Wang, Buhong},
              year = {2019},
              journal = {International Journal of Critical Infrastructure Protection},
              volume = {24},
              pages = {78--99},
              doi = {10.1016/j.ijcip.2018.11.003}
              }`
      },
      {
              id: 2,
              title: "Online Sequential Attack Detection for ADS-B Data Based on Hierarchical Temporal Memory",
              authors: ["Tengyao Li", "Buhong Wang", "Fute Shang", "Jiwei Tian", "Kunrui Cao"],
              venue: "Computers & Security",
              year: 2019,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.cose.2019.101599",
              code: "#",
              highlight: false,
              bibtex: `@article{liOnlineSequentialAttack2019,
              title = {Online Sequential Attack Detection for ADS-B Data Based on Hierarchical Temporal Memory},
              author = {Li, Tengyao and Wang, Buhong and Shang, Fute and Tian, Jiwei and Cao, Kunrui},
              year = {2019},
              journal = {Computers \& Security},
              volume = {87},
              pages = {101599},
              doi = {10.1016/j.cose.2019.101599}
              }`
      }, 
      {
              id: 3,
              title: "Multidevice False Data Injection Attack Models of ADS-B Multilateration Systems",
              authors: ["Fute Shang", "Buhong Wang", "Fuhu Yan", "Tengyao Li"],
              venue: "Security and Communication Networks",
              year: 2019,
              type: "Journal",
              pdf: "https://doi.org/10.1155/2019/8936784",
              code: "#",
              highlight: false,
              bibtex: `@article{shangMultideviceFalseData2019,
              title = {Multidevice False Data Injection Attack Models of ADS-B Multilateration Systems},
              author = {Shang, Fute and Wang, Buhong and Yan, Fuhu and Li, Tengyao},
              editor = {Katzenbeisser, Stefan},
              year = 2019,
              month = mar,
              journal = {Security and Communication Networks},
              volume = {2019},
              pages = {8936784},
              doi = {10.1155/2019/8936784}
              }`
      },
      {
              id: 4,
              title: "ADS-B Data Attack Detection Based on Generative Adversarial Networks",
              authors: ["Tengyao Li", "Buhong Wang", "Fute Shang", "Jiwei Tian", "Kunrui Cao"],
              venue: "International Symposium on Cyberspace Safety and Security",
              year: 2019,
              type: "Conference",
              pdf: "https://doi.org/10.1007/978-3-030-37337-5_26",
              code: "#",
              highlight: false,
              bibtex: `@inproceedings{liADSBDataAttackDetection2019,
              title = {ADS-B Data Attack Detection Based on Generative Adversarial Networks},
              booktitle = {International Symposium on Cyberspace Safety and Security},
              author = {Li, Tengyao and Wang, Buhong and Shang, Fute and Tian, Jiwei and Cao, Kunrui},
              year = 2019,
              series = {Cyberspace Safety and Security},
              pages = {323--336},
              publisher = {Springer International Publishing},
              doi={10.1007/978-3-030-37337-5_26}
              }`
      },
      {
              id: 5,
              title: "Stealthy and Sparse False Data Injection Attacks Based on Machine Learning",
              authors: ["Jiwei Tian", "Buhong Wang", "Tengyao Li", "Fute Shang", "Kunrui Cao", "Jing Li"],
              venue: "International Symposium on Cyberspace Safety and Security",
              year: 2019,
              type: "Conference",
              pdf: "https://doi.org/10.1007/978-3-030-37337-5_27",
              code: "#",
              highlight: false,
              bibtex: `@inproceedings{tianStealthyandSparse2019,
              title = {Stealthy and Sparse False Data Injection Attacks Based on Machine Learning},
              booktitle = {International Symposium on Cyberspace Safety and Security},
              author = {Tian, Jiwei and Wang, Buhong and Li, Tengyao and Shang, Fute and Cao, Kunrui and Li, Jing},
              editor = {Vaidya, Jaideep and Zhang, Xiao and Li, Jin},
              year = 2019,
              series = {Cyberspace Safety and Security},
              pages = {337--347},
              publisher = {Springer International Publishing},
              doi={10.1007/978-3-030-37337-5_27}
              }`
      },
      {
              id: 6,
              title: "Adaptive Normalized Attacks for Learning Adversarial Attacks and Defenses in Power Systems",
              authors: ["Jiwei Tian", "Tengyao Li", "Fute Shang", "Kunrui Cao", "Jing Li", "Mete Ozay"],
              venue: "2019 IEEE International Conference on Communications, Control, and Computing Technologies for Smart Grids (SmartGridComm)",
              year: 2019,
              type: "Conference",
              pdf: "https://doi.org/10.1109/SmartGridComm.2019.8909713",
              code: "#",
              highlight: false,
              bibtex: `@inproceedings{tianAdaptiveNormalizedAttacks2019,
              title = {Adaptive Normalized Attacks for Learning Adversarial Attacks and Defenses in Power Systems},
              booktitle = {2019 IEEE International Conference on Communications, Control, and Computing Technologies for Smart Grids (SmartGridComm)},
              author = {Tian, Jiwei and Li, Tengyao and Shang, Fute and Cao, Kunrui and Li, Jing and Ozay Mete},
              year = 2019,
              month = oct,
              pages = {1--6},
              doi = {10.1109/SmartGridComm.2019.8909713}
              }`
      },
      {
              id: 7,
              title: "基于粒子群优化多核支持向量数据描述的广播式自动相关监视异常数据检测模型",
              authors: ["王布宏", "罗鹏", "李腾耀", "田继伟", "尚福特"],
              venue: "电子与信息学报",
              year: 2020,
              type: "Journal",
              pdf: "https://doi.org/10.11999/JEIT190767",
              code: "#",
              highlight: false,
              bibtex: `@article{wangADSBAnomalyDetectionModel2020,
              title = {基于粒子群优化多核支持向量数据描述的广播式自动相关监视异常数据检测模型},
              author = {王布宏 and 罗鹏 and 李腾耀 and 田继伟 and 尚福特},
              year = 2020,
              journal = {电子与信息学报},
              volume = {42},
              number = {11},
              pages = {2727--2734},
              doi = {10.11999/JEIT190767}
              }`
      },
      {
              id: 8,
              title: "Adversarial Examples on Deep-Learning-Based ADS-B Spoofing Detection",
              authors: ["Fute Shang", "Buhong Wang", "Tengyao Li", "Jiwei Tian", "Kunrui Cao", "Rongxiao Guo"],
              venue: "IEEE Wireless Communications Letters",
              year: 2020,
              type: "Journal",
              pdf: "https://doi.org/10.1109/LWC.2020.3002914",
              code: "#",
              highlight: false,
              bibtex: `@article{shangAdversarialExamplesDeepLearning2020,
              title = {Adversarial Examples on Deep-Learning-Based ADS-B Spoofing Detection},
              author = {Shang, Fute and Wang, Buhong and Li, Tengyao and Tian, Jiwei and Cao, Kunrui and Guo, Rongxiao},
              year = 2020,
              journal = {IEEE Wireless Communications Letters},
              volume = {9},
              number = {10},
              pages = {1734--1737},
              issn = {2162-2345},
              doi = {10.1109/LWC.2020.3002914}
              }`
      },
      {
              id: 9,
              title: "Optimal Relay Selection for Secure NOMA Systems Under Untrusted Users",
              authors: ["Kunrui Cao", "Buhong Wang", "Haihang Ding", "Tengyao Li", "Fengkui Gong"],
              venue: "IEEE Transactions on Vehicular Technology",
              year: 2020,
              type: "Journal",
              pdf: "https://doi.org/10.1109/TVT.2019.2962860",
              code: "#",
              highlight: false,
              bibtex: `@article{caoOptimalRelaySelection2020,
              title = {Optimal Relay Selection for Secure NOMA Systems Under Untrusted Users},
              author = {Cao, Kunrui and Wang, Buhong and Ding, Haihang and Li, Tengyao and Gong, Fengkui},
              year = 2020,
              journal = {IEEE Transactions on Vehicular Technology},
              volume = {69},
              number = {2},
              pages = {1942--1955},
              doi = {10.1109/TVT.2019.2962860},
              }`
      },
      {
              id: 10,
              title: "Secure Transmission Designs for NOMA Systems Against Internal and External Eavesdropping",
              authors: ["Kunrui Cao", "Buhong Wang", "Haihang Ding", "Tengyao Li", "Jiwei Tian", "Fengkui Gong"],
              venue: "IEEE Transactions on Information Forensics and Security",
              year: 2020,
              type: "Journal",
              pdf: "https://doi.org/10.1109/TIFS.2020.2980202",
              code: "#",
              highlight: false,
              bibtex: `@article{caoSecureTransmissionDesigns2020,
              title = {Secure Transmission Designs for NOMA Systems Against Internal and External Eavesdropping},
              author = {Cao, Kunrui and Wang, Buhong and Ding, Haihang and Li, Tengyao and Tian, Jiwei and Gong, Fengkui},
              year = 2020,
              journal = {Ieee Transactions on Information Forensics and Security},
              volume = {15},
              pages = {2930--2943},
              doi = {10.1109/TIFS.2020.2980202}
              }`
      },
      {
              id: 11,
              title: "Dynamic Temporal ADS-B Data Attack Detection Based on sHDP-HMM",
              authors: ["Tengyao Li", "Buhong Wang", "Fute Shang", "Jiwei Tian", "Kunrui Cao"],
              venue: "Computers & Security",
              year: 2020,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.cose.2020.101789",
              code: "#",
              highlight: false,
              bibtex: `@article{liDynamicTemporalADSB2020,
              title = {Dynamic Temporal ADS-B Data Attack Detection Based on sHDP-HMM},
              author = {Li, Tengyao and Wang, Buhong and Shang, Fute and Tian, Jiwei and Cao, Kunrui},
              year = {2020},
              journal = {Computers \& Security},
              volume = {93},
              pages = {101789},
              doi = {10.1016/j.cose.2020.101789}
              }`
      },
      {
              id: 12,
              title: "ADS-B攻击数据弹性恢复方法",
              authors: ["李腾耀", "王布宏", "尚福特", "田继伟", "曹堃锐"],
              venue: "电子与信息学报",
              year: 2020,
              type: "Journal",
              pdf: "https://doi.org/10.11999/JEIT191020",
              code: "#",
              highlight: false,
              bibtex: `@article{liADSBResilientRecovery2020,
              title = {ADS-B攻击数据弹性恢复方法},
              author = {李腾耀 and 王布宏 and 尚福特 and 田继伟 and 曹堃锐},
              year = 2020,
              journal = {电子与信息学报},
              volume = {42},
              number = {10},
              pages = {2365--2373},
              doi = {10.11999/JEIT191020}
              }`
      },
      {
              id: 13,
              title: "Threat Model and Construction Strategy on ADS-B Attack Data",
              authors: ["Tengyao Li", "Buhong Wang", "Fute Shang", "Jiwei Tian", "Kunrui Cao"],
              venue: "IET Information Security",
              year: 2020,
              type: "Journal",
              pdf: "https://doi.org/10.1049/iet-ifs.2018.5635",
              code: "https://github.com/litengyao/adsb-attack-data-generator",
              highlight: false,
              bibtex: `@article{liThreatModelConstruction2020,
              title = {Threat Model and Construction Strategy on ADS-B Attack Data},
              author = {Li, Tengyao and Wang, Buhong and Shang, Fute and Tian, Jiwei and Cao, Kunrui},
              year = 2020,
              journal = {IET Information Security},
              volume = {14},
              number = {5},
              pages = {542--552},
              issn = {1751-8709},
              doi = {10.1049/iet-ifs.2018.5635}
              }`
      },
      {
              id: 14,
              title: "基于BiGRU-SVDD的ADS-B异常数据检测模型",
              authors: ["罗鹏", "王布宏", "李腾耀"],
              venue: "航空学报",
              year: 2020,
              type: "Journal",
              pdf: "https://hkxb.buaa.edu.cn/CN/10.7527/S1000-6893.2020.23878",
              code: "#",
              highlight: false,
              bibtex: `@article{LuoBiGRUSVDD2020,
              title = {基于BiGRU-SVDD的ADS-B异常数据检测模型},
              author = {罗鹏 and 王布宏 and 李腾耀},
              year = 2020,
              journal = {航空学报},
              volume = {41},
              number = {10},
              pages = {281--291},
              doi = {10.7527/S1000-6893.2020.23878}
              }`
      },
      {
              id: 15,
              title: "Coordinated Cyber-Physical Attacks Considering DoS Attacks in Power Systems",
              authors: ["Jiwei Tian", "Buhong Wang", "Tengyao Li", "Fute Shang", "Kunrui Cao"],
              venue: "International Journal of Robust and Nonlinear Control",
              year: 2020,
              type: "Journal",
              pdf: "https://doi.org/10.1002/rnc.4801",
              code: "#",
              highlight: false,
              bibtex: `@article{tianCoordinatedCyberphysicalAttacks2020,
              title = {Coordinated Cyber-Physical Attacks Considering DoS Attacks in Power Systems},
              author = {Tian, Jiwei and Wang, Buhong and Li, Tengyao and Shang, Fute and Cao, Kunrui},
              year = 2020,
              journal = {International Journal of Robust and Nonlinear Control},
              volume = {30},
              number = {11},
              pages = {4345--4358},
              doi = {10.1002/rnc.4801}
              }`
      },
      {
              id: 16,
              title: "An Adaptive-Data-Driven Attack Detection Framework on ADS-B Data",
              authors: ["Tengyao Li"],
              venue: "Preprint",
              year: 2021,
              type: "Preprint",
              pdf: "https://doi.org/10.36227/techrxiv.13728328.v1",
              code: "#",
              highlight: false,
              bibtex: `@article{liAdaptiveDataDrivenAttackDetection2021,
              title = {An Adaptive-Data-Driven Attack Detection Framework on ADS-B Data},
              author = {Li, Tengyao},
              year = 2021,
              journal = {Preprint},
              doi = {10.36227/techrxiv.13728328.v1}
              }`
      },
      {
              id: 17,
              title: "ADS-B Anomaly Data Detection Model Based on VAE-SVDD",
              authors: ["Peng Luo", "Buhong Wang", "Tengyao Li", "Jiwei Tian"],
              venue: "Computers & Security",
              year: 2021,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.cose.2021.102213",
              code: "#",
              highlight: false,
              bibtex: `@article{luoADSBAnomalyData2021,
              title = {ADS-B Anomaly Data Detection Model Based on VAE-SVDD},
              author = {Luo, Peng and Wang, Buhong and Li, Tengyao and Tian, Jiwei},
              year = {2021},
              journal = {Computers \& Security},
              volume = {104},
              pages = {102213},
              doi = {10.1016/j.cose.2021.102213}
              }`
      },
      {
              id: 18,
              title: "TOTAL: Optimal Protection Strategy Against Perfect and Imperfect False Data Injection Attacks on Power Grid Cyber–Physical Systems",
              authors: ["Jiwei Tian", "Buhong Wang", "Tengyao Li", "Fute Shang", "Kunrui Cao", "Rongxiao Guo"],
              venue: "IEEE Internet of Things Journal",
              year: 2021,
              type: "Journal",
              pdf: "https://doi.org/10.1109/JIOT.2020.3009330",
              code: "#",
              highlight: false,
              bibtex: `@article{tianTOTALOptimalProtection2021,
              title = {TOTAL: Optimal Protection Strategy Against Perfect and Imperfect False Data Injection Attacks on Power Grid Cyber-Physical Systems},
              author = {Tian, Jiwei and Wang, Buhong and Li, Tengyao and Shang, Fute and Cao, Kunrui and Guo, Rongxiao},
              year = 2021,
              journal = {IEEE Internet of Things Journal},
              volume = {8},
              number = {2},
              pages = {1001--1015},
              doi = {10.1109/JIOT.2020.3009330}
              }`
      },
      {
              id: 19,
              title: "HeteroTiC: A Robust Network Flow Watermarking Based on Heterogeneous Time Channels",
              authors: ["Tengyao Li", "Kaiyue Liu", "Wangxin Feng", "Chunfang Yang", "Xiangyang Luo"],
              venue: "Computer Networks",
              year: 2022,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.comnet.2022.109424",
              code: "#",
              highlight: false,
              bibtex: `@article{liHeteroTiCRobustNetwork2022,
              title = {HeteroTiC: A Robust Network Flow Watermarking Based on Heterogeneous Time Channels},
              author = {Li, Tengyao and Liu, Kaiyue and Feng, Wangxin and Yang, Chunfang and Luo, Xiangyang},
              year = {2022},
              journal = {Computer Networks},
              volume = {219},
              pages = {109424},
              doi = {10.1016/j.comnet.2022.109424}
              }`
      },
      {
              id: 20,
              title: "基于动态间隔压缩的鲁棒网络流水印算法",
              authors: ["马香港", "李腾耀", "刘粉林", "冯王昕", "杨春芳"],
              venue: "计算机应用研究",
              year: 2023,
              type: "Journal",
              pdf: "https://www.arocmag.cn/abs/2023.01.0039",
              code: "#",
              highlight: false,
              bibtex: `@article{maRobustNetworkFlowWatermarking2023,
              title = {基于动态间隔压缩的鲁棒网络流水印算法},
              author = {马香港 and 李腾耀 and 刘粉林 and 冯王昕 and 杨春芳},
              year = 2023,
              journal = {计算机应用研究},
              volume = {40},
              number = {10},
              pages = {3144-3148+3154},
              issn = {1001-3695},
              doi = {10.19734/j.issn.1001-3695.2023.01.0039}
              }`
      },
      {
              id: 21,
              title: "HSTW: A Robust Network Flow Watermarking Method Based on Hybrid Packet Sequence-Timing",
              authors: ["Wangxin Feng", "Xiangyang Luo", "Tengyao Li", "Chunfang Yang"],
              venue: "Computers & Security",
              year: 2024,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.cose.2024.103701",
              code: "#",
              highlight: false,
              bibtex: `@article{fengHSTWRobustNetwork2024,
              title = {HSTW: A Robust Network Flow Watermarking Method Based on Hybrid Packet Sequence-Timing},
              author = {Feng, Wangxin and Luo, Xiangyang and Li, Tengyao and Yang, Chunfang},
              year = 2024,
              month = apr,
              journal = {Computers \& Security},
              volume = {139},
              pages = {103701},
              doi = {10.1016/j.cose.2024.103701}
              }`
      },
      {
              id: 22,
              title: "抗扰动的网站指纹鲁棒识别方法",
              authors: ["张静茜", "李腾耀*", "涂宇宽", "罗向阳"],
              venue: "网络与信息安全学报",
              year: 2024,
              type: "Journal",
              pdf: "https://doi.org/10.11959/j.issn.2096-109x.2024086",
              code: "#",
              highlight: false,
              bibtex: `@article{zhangRobustWebsiteFingerpringting2024,
              title = {抗扰动的网站指纹鲁棒识别方法},
              author = {张静茜 and 李腾耀 and 涂宇宽 and 罗向阳},
              year = 2024,
              journal = {网络与信息安全学报},
              volume = {10},
              number = {6},
              pages = {137--150},
              doi = {10.11959/j.issn.2096-109x.2024086}
              }`
      },
      {
              id: 23,
              title: "WF3A: A N-shot Website Fingerprinting with Effective Fusion Feature Attention",
              authors: ["Zhiquan Wang", "Tengyao Li", "Meijuan Yin", "Xiaoyun Yuan", "Xiangyang Luo", "Lingling Li"],
              venue: "Computers & Security",
              year: 2024,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.cose.2024.103796",
              code: "#",
              highlight: false,
              bibtex: `@article{wangWF3ANshotWebsite2024,
              title = {WF3A: A N-shot Website Fingerprinting with Effective Fusion Feature Attention},
              author = {Wang, Zhiquan and Li, Tengyao and Yin, Meijuan and Yuan, Xiaoyun and Luo, Xiangyang and Li, Lingling},
              year = 2024,
              month = may,
              journal = {Computers \& Security},
              volume = {140},
              pages = {103796},
              doi = {10.1016/j.cose.2024.103796}
              }`
      },
      {
              id: 24,
              title: "IP-Pealing: A Robust Network Flow Watermarking Method Based on IP Packet Sequence",
              authors: ["Wangxin Feng", "Xiangyang Luo", "Tengyao Li", "Chunfang Yang"],
              venue: "Chinese Journal of Electronics",
              year: 2024,
              type: "Journal",
              pdf: "https://doi.org/10.23919/cje.2022.00.366",
              code: "#",
              highlight: false,
              bibtex: `@article{wangxinIPPealingRobustNetwork2024,
              title = {IP-Pealing: A Robust Network Flow Watermarking Method Based on IP Packet Sequence},
              author = {Feng, Wangxin and Luo, Xiangyang and Li Tengyao and Yang, Chunfang},
              year = 2024,
              journal = {Chinese Journal of Electronics},
              volume = {33},
              number = {3},
              pages = {694--707},
              doi = {10.23919/cje.2022.00.366}}`
      },
      {
              id: 25,
              title: "HSWF: Enhancing Website Fingerprinting Attacks on Tor to Address Real World Distribution Mismatch",
              authors: ["Xiaoyun Yuan", "Tengyao Li", "Lingling Li", "Ruixiang Li", "Zhiquan Wang", "Xiangyang Luo"],
              venue: "Computer Networks",
              year: 2024,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.comnet.2024.110217",
              code: "#",
              highlight: false,
              bibtex: `@article{yuanHSWFEnhancingWebsite2024,
              title = {HSWF: Enhancing Website Fingerprinting Attacks on Tor to Address Real World Distribution Mismatch},
              author = {Yuan, Xiaoyun and Li, Tengyao and Li, Lingling and Li, Ruixiang and Wang, Zhiquan and Luo, Xiangyang},
              year = 2024,
              month = mar,
              journal = {Computer Networks},
              volume = {241},
              pages = {110217},
              doi = {10.1016/j.comnet.2024.110217}
              }`
      },
      {
              id: 26,
              title: "MVC-Corr: An Accurate and Efficient Flow Correlation Method Based on Multi-View Fusion and Contrast Augmentation",
              authors: ["YuKuan Tu", "Tengyao Li", "Meng Zhang", "Xiangyang Luo"],
              venue: "Computer Networks",
              year: 2025,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.comnet.2025.111439",
              code: "#",
              highlight: false,
              bibtex: `@article{tuMVCCorrAnAccurateandEfficientFlow2025,
              title = {MVC-Corr: An Accurate and Efficient Flow Correlation Method Based on Multi-View Fusion and Contrast Augmentation},
              author = {Tu, YuKuan and Li, Tengyao and Zhang, Meng and Luo, Xiangyang},
              year = 2025,
              journal = {Computer Networks},
              volume = {269},
              pages = {111439},
              doi = {10.1016/j.comnet.2025.111439}
              }`
      },
      {
              id: 27,
              title: "An Efficient Website Fingerprinting for New Websites Emerging Based on Incremental Learning",
              authors: ["Zhengge Yi", "Tengyao Li", "Meng Zhang", "Xiaoyun Yuan", "Shaoyong Du", "Xiangyang Luo"],
              venue: "IEEE Transactions on Network and Service Management",
              year: 2026,
              type: "Journal",
              pdf: "https://doi.org/10.1109/tnsmb.2025.3627441",
              code: "#",
              highlight: false,
              bibtex: `@article{yiEfficientWebsiteFingerprinting2026,
              title = {An Efficient Website Fingerprinting for New Websites Emerging Based on Incremental Learning},
              author = {Yi, Zhengge and Li, Tengyao and Zhang, Meng and Yuan, Xiaoyun and Du, Shaoyong and Luo, Xiangyang},
              year = 2026,
              journal = {IEEE Transactions on Network and Service Management},
              volume = {23},
              pages = {365--381},
              issn = {1932-4537},
              doi = {10.1109/TNSM.2025.3627441}
              }`
      },
      {
              id: 28,
              title: "A Survey on Network Flow Watermarking: A Problem-Oriented Perspective",
              authors: ["Tengyao Li", "Kaiyue Liu", "Shaoyong Du"],
              venue: "Computers & Security",
              year: 2026,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.cose.2025.104813",
              code: "#",
              highlight: false,
              bibtex: `@article{liSurveyonNetworkFlowWatermarking2026,
              title = {A Survey on Network Flow Watermarking: A Problem-Oriented Perspective},
              author = {Li, Tengyao and Liu, Kaiyue and Du, Shaoyong},
              year = 2026,
              journal = {Computers \& Security},
              volume = {163},
              pages = {104813},
              doi = {10.1016/j.cose.2025.104813}
              }`
      },
      {
              id: 29,
              title: "A Self-Adaptive Network Flow Watermarking with Robust Synchronization",
              authors: ["Tengyao Li", "Kaiyue Liu", "Shichang Ding", "Chunfang Yang", "Xiangyang Luo"],
              venue: "Computer Networks",
              year: 2026,
              type: "Journal",
              pdf: "https://doi.org/10.1016/j.comnet.2026.112106",
              code: "#",
              highlight: false,
              bibtex: `@article{liSelfAdaptiveNetworkFlowWatermarking2026,
              title = {A Self-Adaptive Network Flow Watermarking with Robust Synchronization},
              author = {Li, Tengyao and Liu, Kaiyue and Ding, Shichang and Yang, Chunfang and Luo, Xiangyang},
              year = 2026,
              journal = {Computer Networks},
              volume = {278},
              pages = {112106},
              doi = {10.1016/j.comnet.2026.112106}
              }`
      }
      ]

      // 默认按年份降序，同年份内按 ID 或标题排序（这里简单按 ID）
      publications.value.sort((a, b) => b.year - a.year || b.id - a.id)

    } catch (e) {
      error.value = "Failed to load publications."
      console.error(e)
    } finally {
      loading.value = false
    }
  }

  onMounted(() => {
    fetchPublications()
  })

  return { publications, loading, error }
}